bindkey "^@" undefined-key
bindkey "^A" undefined-key
bindkey "^B" undefined-key
bindkey "^D" undefined-key
bindkey "^E" undefined-key
bindkey "^F" undefined-key
bindkey "^G" undefined-key
bindkey "^H" undefined-key
bindkey "^I" undefined-key
bindkey "^J" undefined-key
bindkey "^K" undefined-key
bindkey "^L" undefined-key
bindkey "^M" undefined-key
bindkey "^N" undefined-key
bindkey "^O" undefined-key
bindkey "^P" undefined-key
bindkey "^Q" undefined-key
bindkey "^R" undefined-key
bindkey "^S" undefined-key
bindkey "^T" undefined-key
bindkey "^U" undefined-key
bindkey "^V" undefined-key
bindkey "^W" undefined-key
bindkey "^X^B" undefined-key
bindkey "^X^F" undefined-key
bindkey "^X^J" undefined-key
bindkey "^X^K" undefined-key
bindkey "^X^N" undefined-key
bindkey "^X^O" undefined-key
bindkey "^X^U" undefined-key
bindkey "^X^V" undefined-key
bindkey "^X^X" undefined-key
bindkey "^X*" undefined-key
bindkey "^X=" undefined-key
bindkey "^XG" undefined-key
bindkey "^Xg" undefined-key
bindkey "^Xr" undefined-key
bindkey "^Xs" undefined-key
bindkey "^Xu" undefined-key
bindkey "^Y" undefined-key
bindkey "^[^D" undefined-key
bindkey "^[^G" undefined-key
bindkey "^[^H" undefined-key
bindkey "^[^I" undefined-key
bindkey "^[^J" undefined-key
bindkey "^[^L" undefined-key
bindkey "^[^M" undefined-key
bindkey "^[^_" undefined-key
bindkey "^[ " undefined-key
bindkey "^[!" undefined-key
bindkey "^[\"" undefined-key
bindkey "^[\$" undefined-key
bindkey "^['" undefined-key
bindkey "^[-" undefined-key
bindkey "^[." undefined-key
bindkey "^[0" undefined-key
bindkey "^[1" undefined-key
bindkey "^[2" undefined-key
bindkey "^[3" undefined-key
bindkey "^[4" undefined-key
bindkey "^[5" undefined-key
bindkey "^[6" undefined-key
bindkey "^[7" undefined-key
bindkey "^[8" undefined-key
bindkey "^[9" undefined-key
bindkey "^[<" undefined-key
bindkey "^[>" undefined-key
bindkey "^[?" undefined-key
bindkey "^[A" undefined-key
bindkey "^[B" undefined-key
bindkey "^[C" undefined-key
bindkey "^[D" undefined-key
bindkey "^[F" undefined-key
bindkey "^[G" undefined-key
bindkey "^[H" undefined-key
bindkey "^[L" undefined-key
bindkey "^[N" undefined-key
bindkey "^[OA" undefined-key
bindkey "^[OB" undefined-key
bindkey "^[OC" undefined-key
bindkey "^[OD" undefined-key
bindkey "^[P" undefined-key
bindkey "^[Q" undefined-key
bindkey "^[S" undefined-key
bindkey "^[T" undefined-key
bindkey "^[U" undefined-key
bindkey "^[W" undefined-key
bindkey "^[[200~" undefined-key
bindkey "^[[A" undefined-key
bindkey "^[[B" undefined-key
bindkey "^[[C" undefined-key
bindkey "^[[D" undefined-key
bindkey "^[_" undefined-key
bindkey "^[a" undefined-key
bindkey "^[b" undefined-key
bindkey "^[c" undefined-key
bindkey "^[d" undefined-key
bindkey "^[f" undefined-key
bindkey "^[g" undefined-key
bindkey "^[h" undefined-key
bindkey "^[l" undefined-key
bindkey "^[n" undefined-key
bindkey "^[p" undefined-key
bindkey "^[q" undefined-key
bindkey "^[s" undefined-key
bindkey "^[t" undefined-key
bindkey "^[u" undefined-key
bindkey "^[w" undefined-key
bindkey "^[x" undefined-key
bindkey "^[y" undefined-key
bindkey "^[z" undefined-key
bindkey "^[|" undefined-key
bindkey "^[^?" undefined-key
bindkey "^_" undefined-key
bindkey " "-"~" undefined-key
bindkey "^?" undefined-key
bindkey "\M-^@"-"\M-^?" undefined-key
