#+TITLE: zwsh
A Zpm3/Wordstar mode/theme for zsh

* Description
A zsh mode that uses Zpm3/Wordstar keybindings and functionality.  It can
 - select copy and move blocks of text,
 - edit multiline commands,
 - import and export from and to files.

* Other doc files
 + [[doc/wsblock.org][wsblock]]
 + [[doc/wsdialog.org][wsdialog]]
 + [[doc/wsedit.org][wsedit]]
 + [[doc/wsfind.org][wsfind]]
 + [[doc/wskeys.org][key description]]
 + [[doc/wstext.org][the concept of separating the text from the screen]]

* Tests
The directory *tests* contains tests to test different modules independently
from the whole application.  Also allows to test features and cases rarely or
not used in the main application, which could be useful in future versions.

---------

* To do plan
** wsline
 + Test edit, navigation, functionality

** wsedit
Without implementing wsblock keybindings, finish wsedit mode:
 + keybindings
 + import from file
 + exit saving / not saving / putting into buffer wsedit mode
 + enter wsedit mode: using buffer / using file
 + add fullscreen mode and vertical scroll

** wsblock
Rewrite wsblock for edit, normal and wsline modes:
 + review wsblock specifications, redefine behaviour, parameters, variables...
 + implement marks: places that move with the text: track position, column, line (also for wsline)
 + reimplement block functionality, on wsline, substitute CR's and LF's with a normal character, like space or a special substitution character (in order to restore space if copying to edit or normal mode)
 + test on normal, edit and wsline modes
 + add column selection

** add superuser functionality
 + if no right to read/write, display superuser prompt 
 + when opening read only file: add to status bar (? disallow editing ?)
